apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app2
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: nginx
        image: "{{.Values.app2.image}}"
        imagePullPolicy: Never
        ports:
        - containerPort: 80
